### ISSUE TITLE
Can not pass the verification

### ISSUE THREAD

**Issue by billqxg** [ZhouYanzhao/PRM#7]
Execute " nest module list --filter prm" and get the following result.(Ubuntu16)

(pt-py3) root@ebe535e9a1a8:~# nest module list --filter prm
Traceback (most recent call last):
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 346, in _import_nest_modules_from_file
    spec.loader.exec_module(py_module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/PRM/install/prm.py", line 30, in <module>
    filter_type: Union[str, int, float] = 'median') -> nn.Module:
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 262, in _register
    return create_module(args[0])
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 259, in create_module
    return type('NestModule', (NestModule,), dict(__slots__=(), __doc__=doc))(func, nest_meta)
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 69, in __init__
    self._check_definition()
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 80, in _check_definition
    if v.default is not inspect.Parameter.empty and not U.is_annotation_matched(v.default, v.annotation):
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/logger.py", line 59, in wrapper
    res = func(*args, **kwargs)
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/utils.py", line 236, in is_annotation_matched
    sub_annotation = annotation.__args__
AttributeError: type object 'Union' has no attribute '__args__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Envs/pt-py3/bin/nest", line 11, in <module>
    sys.exit(main())
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/__main__.py", line 4, in main
    CLI()
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/cli.py", line 71, in __init__
    getattr(self, 'cmd_' + args.command)('nest ' + args.command, sys.argv[2:])
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/cli.py", line 162, in cmd_module
    module_info = ['%s (%s)' % (k, v.meta.get('version', 'version')) for k, v in module_manager]
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 702, in __iter__
    self._update_modules()
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 692, in _update_modules
    ModuleManager._import_nest_modules_from_dir(meta['module_path'], namespace, self.py_modules, self.nest_modules, meta)
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 407, in _import_nest_modules_from_dir
    ModuleManager._import_nest_modules_from_file(file_path, namespace, py_modules, nest_modules, meta)
  File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 356, in _import_nest_modules_from_file
    if (type(exc_info) is ModuleNotFoundError or type(exc_info) is ImportError) and exc_info.name is not None:
NameError: name 'ModuleNotFoundError' is not defined

**Comment by ZhouYanzhao** [comment]
Hi @doudoubilly 
This seems to be a Nest related issue and it will be tracked in https://github.com/ZhouYanzhao/Nest/issues/1. Thanks!
